#! /bin/sh

# DOTTIES_DIR=$(find $HOME -type d -name "dotties")
# LOCATION=$(curl -s "https://location.services.mozilla.com/v1/geolocate?key=geoclue" -m 10 --connect-timeout 10 | awk 'OFS=":" {print $3,$5}' | tr -d ',}')

# Fall back to hardcoded location if I am offline
# Currently I am in Vietnam, so default Vietnam?
# if [[ -z $LOCATION ]]
# then
#    LOCATION="10.8326:106.6581"
# fi

LOCATION="10.8326:106.6581"
DOTTIES_DIR="$HOME/dotties"

# Kill processes
killall xborders
killall picom
killall polybar
killall redshift
killall redshift-gtk
killall nm-applet
killall pasystray
killall dunst
killall sxhkd
killall ibus-daemon
killall greenclip
killall plank
killall feh
killall xfce-polkit

picom &
feh --bg-fill $DOTTIES_DIR/assets/desktop.png --no-fehbg
polybar -c $HOME/.config/polybar/config.ini top_left &
polybar -c $HOME/.config/polybar/config.ini top_center &
polybar -c $HOME/.config/polybar/config.ini top_right &
polybar -c $HOME/.config/polybar/config.ini bottom_left &
polybar -c $HOME/.config/polybar/config.ini bottom_right &
sxhkd -c $HOME/.config/bspwm/sxhkdrc &
redshift-gtk -l $LOCATION &
nm-applet &
pasystray &
dunst &
ibus-daemon -drx &
greenclip daemon &
plank &
/usr/lib/xfce-polkit/xfce-polkit &

# ================================
bspc monitor -d 1 2 3 4
bspc config window_gap          8

bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config border_width 5
bspc config active_border_color \#F0C674
bspc config focused_border_color \#F0C674
bspc config normal_border_color none

bspc rule -a Pavucontrol state=floating
bspc rule -a GitKraken state=floating
