#!/bin/bash

export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT4_IM_MODULE=ibus
export _JAVA_AWT_WM_NONREPARENTING=1

# If you use the patch:
# https://github.com/andreasgrafen/pfetch-with-kitties
# export PF_ASCII="Catppuccin"

# DOTTIES_DIR=$(find $HOME -type d -name "dotties")
# LOCATION=$(curl -s "https://location.services.mozilla.com/v1/geolocate?key=geoclue" -m 10 --connect-timeout 10 | awk 'OFS=":" {print $3,$5}' | tr -d ',}')
LOCATION="10.8326:106.6581"
DOTTIES_DIR="$HOME/dotties"
POLYBAR="polybar -c $HOME/.config/polybar/config.ini"
EWW="eww -c $HOME/.config/eww/hosf"

# Kill processes
killall cbatticon
killall easyeffects
killall alttab
killall picom
killall polybar
killall redshift
killall redshift-gtk
killall nm-applet
killall pasystray
killall sxhkd
killall ibus-daemon
killall greenclip
killall eww
killall polkit-gnome-authentication-agent-1
killall flameshot
killall xbacklight-notify
killall dunst
killall mpv
killall xwinwrap

# Start apps
picom --experimental-backends &
$POLYBAR top_left &
$POLYBAR top_center &
$POLYBAR top_right &
$POLYBAR power_button &
# $POLYBAR bottom_left &
$POLYBAR bottom_middle &
$POLYBAR bottom_right &
sxhkd -c $HOME/.config/bspwm/sxhkdrc &
$EWW daemon &
redshift-gtk -l $LOCATION &
nm-applet &
pasystray &
ibus-daemon -drx &
greenclip daemon &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
cbatticon -u 2 &
xbacklight-notify --timeout 1 &
flameshot &
alttab -w 1 -fg "#d58681" -bg "#4a4a4a" -frame "#f0c674" -t 128x150 -i 127x64 -font "Jetbrains Mono" &

# Easy effects setup
if ! pgrep -f /usr/bin/easyeffects; then
    easyeffects --gapplication-service &
fi

# Wallpaper setup
if [ $(cat $HOME/.config/bspwm/wallpaper_mode.txt) = "A" ];
then
    xwinwrap -fs -fdt -ni -b -nf -- \
        mpv --no-audio --loop --hwdec=vaapi -wid %WID $HOME/dotties/assets/hosf_trim.mp4 &
else
    feh --bg-fill $DOTTIES_DIR/assets/hosf.png --no-fehbg
fi

# https://wiki.archlinux.org/title/bspwm#Problems_with_Java_applications
export _JAVA_AWT_WM_NONREPARENTING=1
wmname Amiya

# ===============================
#  BSPWM zone
# ===============================
bspc monitor -d 1 2 3 4 5 6 7
bspc config window_gap          10
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc config split_ratio                 0.5
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true
bspc config borderless_monocle          true
bspc config gapless_monocle             true

bspc config border_width 4
bspc config active_border_color "#F0C674"
bspc config focused_border_color "#F0C674"
bspc config urgent_border_color "#FF0000"

bspc rule -a viewnior       state=floating center=true
bspc rule -a Pavucontrol    state=floating center=true
bspc rule -a Rofi			manage=off
bspc rule -a PeaZip         state=floating center=true
bspc rule -a easyeffects    state=floating center=true
# ============ Hi ! ==============
notify-send "Hello, $USER" "Welcome aboard!"
# ================================
