#!/bin/bash

# DOTTIES_DIR=$(find $HOME -type d -name "dotties")
# LOCATION=$(curl -s "https://location.services.mozilla.com/v1/geolocate?key=geoclue" -m 10 --connect-timeout 10 | awk 'OFS=":" {print $3,$5}' | tr -d ',}')
LOCATION="10.8326:106.6581"
DOTTIES_DIR="$HOME/dotties"
POLYBAR="polybar -c $HOME/.config/polybar/config.ini"
EWW="eww -c $HOME/.config/eww/hosf"

# Kill processes
killall picom
killall polybar
killall redshift
killall redshift-gtk
killall nm-applet
killall pasystray
killall sxhkd
killall ibus-daemon
killall greenclip
killall eww
killall xfce-polkit
killall xfce4-power-manager
killall flameshot
killall komorebi
killall flameshot

# Set wallpaper?
if [ $(cat $HOME/.config/bspwm/wallpaper_mode.txt) == "A" ]
then
    komorebi &
else
    feh --bg-fill $DOTTIES_DIR/assets/desktop.png --no-fehbg
fi

# Start apps
picom --experimental-backend &
$POLYBAR top_workspaces &
$POLYBAR top_center &
$POLYBAR top_right &
# $POLYBAR bottom_left &
$POLYBAR bottom_middle &
$POLYBAR bottom_right &
sxhkd -c $HOME/.config/bspwm/sxhkdrc &
$EWW daemon &
redshift-gtk -l $LOCATION &
nm-applet &
pasystray &
ibus-daemon -drx &
greenclip daemon &
/usr/lib/xfce-polkit/xfce-polkit &
xfce4-power-manager --daemon
flameshot &

# ================================

bspc monitor -d 1 2 3 4 5 6 7
bspc config window_gap          10
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc config split_ratio                 0.5
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true
bspc config borderless_monocle          true
bspc config gapless_monocle             true

bspc config border_width 4
bspc config normal_border_color "#1f1e33"
bspc config active_border_color "#FFB6C1"
bspc config focused_border_color "#FFB6C1"
bspc config urgent_border_color "#FF0000"

bspc rule -a viewnior       state=floating center=true
bspc rule -a Pavucontrol    state=floating
bspc rule -a Rofi			manage=off

# https://wiki.archlinux.org/title/bspwm#Problems_with_Java_applications
wmname LG3D
