(()=>{"use strict";const e={args:[e=>{const t=Object.call,n=t.bind(t),o=!(console.exception||![].at),r=Object.getOwnPropertyDescriptor;return{__proto__:null,sourceWindow:e,F_c:n,F_a:Object.apply,F_b:Object.bind,F_tS:Function.toString,A_fE:[].forEach,A_so:[].some,A_sp:[].splice,A_sh:[].shift,A_j:[].join,A_po:[].pop,A_m:[].map,A_f:[].filter,A_iO:[].indexOf,A_iA:Array.isArray,O_a:Object.assign,O_k:Object.keys,O_v:Object.values,O_dP:Object.defineProperties,O_dPy:Object.defineProperty,
O_hOP:Object.hasOwnProperty,O_gOPN:Object.getOwnPropertyNames,O_gOPD:r,O_gOPDs:Object.getOwnPropertyDescriptors,O_gPO:Object.getPrototypeOf,O_tS:{}.toString,J_p:JSON.parse,J_s:JSON.stringify,c_l:o?console.log:null,c_i:o?console.info:null,c_w:o?console.warn:null,c_e:o?console.error:null,c_d:o?console.debug:null,M_f:Math.floor,M_r:Math.random,M_m:Math.max,M_i:MutationEvent.prototype.initMutationEvent,M_pA:MutationEvent.prototype.ADDITION,M_pAT:MutationEvent.AT_TARGET,N_tS:(0).toString,
N_MSI:Number.MAX_SAFE_INTEGER,P_t:Promise.prototype.then,P_c:Promise.prototype.catch,R_rABS:FileReader.prototype.readAsBinaryString,R_rAT:FileReader.prototype.readAsText,R_enq:e.ReadableStreamDefaultController?e.ReadableStreamDefaultController.prototype.enqueue:null,R_cl:e.ReadableStreamDefaultController?e.ReadableStreamDefaultController.prototype.close:null,S_fCC:String.fromCharCode,S_m_nr:"".match,S_sl:"".slice,S_su:"".substr,S_se_nr:"".search,S_sp_nr:"".split,S_tr:"".trim,S_r_nr:"".replace,
S_rA_nr:"".replaceAll,S_cCA:"".charCodeAt,S_tLC:"".toLowerCase,S_tUC:"".toUpperCase,Y_tST:Symbol.toStringTag,D_pFS:DOMParser.prototype.parseFromString,U_cOU:URL.createObjectURL,U_rOU:URL.revokeObjectURL,X_o:XMLHttpRequest.prototype.open,X_pSD:XMLHttpRequest.prototype.DONE,X_pSH:XMLHttpRequest.prototype.HEADERS_RECEIVED,X_pSL:XMLHttpRequest.prototype.LOADING,X_pSO:XMLHttpRequest.prototype.OPENED,X_pSU:XMLHttpRequest.prototype.UNSENT,X_s:XMLHttpRequest.prototype.send,D_n:Date.now,I_tS:e=>""+e,
E_r:Element.prototype.remove,D_cS:r(Document.prototype,"currentScript").get,M_aN:r(MutationEvent.prototype,"attrName").get,M_rN:r(MutationEvent.prototype,"relatedNode").get,C_d:r(CustomEvent.prototype,"detail").get,parseInt,parseFloat,CustomEvent,KeyboardEvent,MouseEvent,MutationEvent,console,Error,Uint8Array,Blob,Number,String,Proxy,Window,encodeURIComponent,decodeURIComponent,encodeURI,decodeURI,escape,unescape,atob,btoa,postMessage,dispatchEvent,addEventListener,removeEventListener,alert,
prompt,confirm,close,getElementById:e.Document.prototype.getElementById,createEvent:e.Document.prototype.createEvent,createElement:e.Document.prototype.createElement}},(e,t)=>{
const{F_c:n,F_a:o,O_dPy:r,O_a:s,O_gOPD:a,O_gOPN:i,O_gPO:c}=e,{F_c:l,F_b:d,F_tS:u,A_fE:p,A_so:m,A_sh:g,A_j:f,A_po:_,A_m:v,A_f:h,A_iO:b,A_iA:w,O_a:y,O_k:M,O_v:E,O_dP:S,O_dPy:L,O_hOP:x,O_gOPN:O,O_gOPD:C,O_gOPDs:T,O_gPO:R,O_tS:U,J_p:A,J_s:P,c_l:D,c_i:I,c_w:k,c_e:N,c_d:G,M_f:j,M_r:F,M_m:$,M_i:V,M_pA:q,M_pAT:B,N_tS:X,N_MSI:H,P_t:J,P_c:W,R_rABS:K,R_rAT:Y,R_enq:z,R_cl:Q,S_fCC:Z,S_m_nr:ee,S_sl:te,S_su:ne,S_se_nr:oe,S_sp_nr:re,S_tr:se,S_r_nr:ae,S_rA_nr:ie,S_cCA:ce,S_tLC:le,S_tUC:de,Y_tST:ue,D_pFS:pe,D_cS:me,E_r:ge,M_aN:fe,M_rN:_e,C_d:ve,U_cOU:he,U_rOU:be,X_o:we,X_s:ye,X_pSD:Me,X_pSH:Ee,X_pSL:Se,X_pSO:Le,X_pSU:xe,D_n:Oe,I_tS:Ce,parseInt:Te,parseFloat:Re,console:Ue,encodeURIComponent:Ae,decodeURIComponent:Pe,encodeURI:De,decodeURI:Ie,escape:ke,unescape:Ne,atob:Ge,btoa:je,postMessage:Fe,dispatchEvent:$e,addEventListener:Ve,removeEventListener:qe,alert:Be,prompt:Xe,confirm:He,close:Je,getElementById:We,createEvent:Ke,createElement:Ye,CustomEvent:ze,KeyboardEvent:Qe,MouseEvent:Ze,MutationEvent:et,Uint8Array:tt,Blob:nt,Number:ot,String:rt,Proxy:st,Window:at}=e,it=(e,t,r)=>n(o,e,t,r),ct=e=>s({
__proto__:null},e),lt=(e,t,n)=>(r(e,t,ct({value:n,configurable:!0,enumerable:!0,writable:!0})),e),dt=(e,t)=>yt(e,t)?e[t]:void 0,ut=(e,t)=>{const n=a(e,t);return n?ct(n).value:void 0},pt=(e,t)=>{const n=(e,t,o)=>{const r=a(e,t),s=r?ct(r):void 0;let i;return s?s.enumerable?s.value:void 0:--o>=0&&(i=c(e))?n(i,t,o):void 0};return n(e,t,5)},mt=e=>{const t=(t,...n)=>it(e,t,n);return lt(t,"wrappedJSObject",e),t},gt=()=>e=>mt(e),ft=gt()(d),_t=(e,t,n)=>{const o=e.length;let r=t||0;if(r>=o)return[]
;r<0&&(r=$(0,o+r));let s=void 0===n?o:n;s<0&&(s=$(0,o+s)),s>o&&(s=o);const a=ct({});for(let t=r;t<s;t++)a[t]=ut(e,t);return E(a)},vt=gt()(f),ht=(e,...t)=>{let n=e.length;const o=ct(e);for(let e=0;e<t.length;e++){const r=t[e],s=w(r)?r:[r];for(let e=0;e<s.length;e++)o[n+e]=ut(s,e);n+=s.length}return E(o)},bt=gt()(b),wt=gt()(p),yt=gt()(x),Mt=gt()(re),Et=gt()(te),St=mt(U),Lt=c({}),xt=e=>{const t=ct(e),n=i(t);for(let e=0;e<n.length;e++){const o=n[e],r=t[o]
;null!==r&&"object"==typeof r&&c(r)===Lt&&(t[o]=xt(r))}return t},Ot=(Ct=ct({a:"decodeURI",b:"Component"})).a+Ct.b;var Ct;const Tt=D?void 0:dt(t,"console");return ct({cSO:ct,pO:xt,gOP:dt,gOPV:ut,sOP:lt,tT:e=>{const t=Mt(St(e,ct({}))," ");return Et(vt(_t(t,1)," "),0,-1)},f:ct({call:n,F_a:it,F_c:l,F_b:ft,F_tS:gt()(u),A_fE:wt,A_sl:_t,A_so:gt()(m),A_sp:(e,t,n,...o)=>{const r=o||[],s=_t(e,0,t),a=_t(e,t,n),i=_t(e,t+n);let c=ht([],s);return c=ht(c,r),c=ht(c,i),ct({result:c,removed:a})},A_sh:gt()(g),
A_j:vt,A_po:gt()(_),A_m:gt()(v),A_c:ht,A_f:gt()(h),A_iO:bt,O_a:y,O_k:M,O_dP:S,O_dPy:L,O_hOP:x,O_gOPN:O,O_gOPD:C,O_gOPDs:T||(e=>{const t=ct({});for(const n in e)t[n]=a(e,n);return t}),O_gPO:R,O_tS:St,J_p:A,J_ss:e=>{const t=(e,n)=>{let o;if(null===e)o="null";else if("object"==typeof e){if(n){if(-1!=bt(n,e))throw"Converting circular structure to JSON";lt(n,n.length,e)}else n=[e];if(w(e)){let r="";for(let o=0;o<e.length;o++){let s;s=yt(e,o)?dt(e,o):pt(e,o);const a=t(s,n)
;r+=`${o?",":""}${void 0===a?"null":a}`}o=`[${r}]`}else{let r="";wt(M(e),o=>{const s=t(e[o],n);void 0!==s&&(r+=`${r?",":""}${P(o)}: ${s}`)}),o=`{${r}}`}n.length-=1}else o=P(e);return o};return t(e)},J_n:e=>{const t=A(e),n=e=>{const t=[];for(let n=0;n<e.length;n++)lt(t,n,o(e[n]));return t},o=e=>{if(null===e);else if("object"==typeof e){if(w(e))return n(e);{const t={};return wt(M(e),r=>{const s=e[r];let a;a="object"==typeof s?w(s)?n(s):o(s):s,lt(t,r,a)}),t}}return e};return o(t)},
c_l:D||dt(Tt,"log")||(()=>{}),c_i:I||dt(Tt,"info")||(()=>{}),c_w:k||dt(Tt,"warn")||(()=>{}),c_e:N||dt(Tt,"error")||(()=>{}),c_d:G||dt(Tt,"debug")||(()=>{}),M_f:j,M_r:F,M_m:$,M_i:gt()(V),M_pA:q,M_pAT:B,N_tS:gt()(X),N_MSI:H,P_r:async e=>e,P_t:gt()(J),P_c:gt()(W),R_rABS:gt()(K),R_rAT:gt()(Y),R_enq:z?gt()(z):z,R_cl:Q?gt()(Q):Q,S_fCC:Z,S_m_nr:gt()(ee),S_sl:Et,S_su:gt()(ne),S_se_nr:gt()(oe),S_sp_nr:Mt,S_tr:gt()(se),S_r_nr:gt()(ae),S_rA_nr:gt()(ie||function(e,t){return vt(Mt(this,e),t)}),
S_cCA:gt()(ce),S_tLC:gt()(le),S_tUC:gt()(de),Y_tST:ue,D_pFS:mt(pe),D_cS:mt(me),E_r:mt(ge),M_aN:mt(fe),M_rN:mt(_e),C_d:mt(ve),U_cOU:he,U_rOU:be,X_o:gt()(we),X_s:gt()(ye),X_pSD:Me,X_pSH:Ee,X_pSL:Se,X_pSO:Le,X_pSU:xe,D_n:Oe,I_tS:Ce}),w_o:ct({Proxy:st,Window:at,Number:ot,String:rt}),w:ct({console:Ue,CustomEvent:ze,KeyboardEvent:Qe,MouseEvent:Ze,MutationEvent:et,Uint8Array:tt,Blob:nt,Promise:ut(c((async()=>{})()),"constructor"),Array:ut(c([]),"constructor")}),w_f:ct({encodeURIComponent:Ae,[Ot]:Pe,
encodeURI:De,decodeURI:Ie,escape:ke,unescape:Ne,atob:Ge,btoa:je,parseInt:Te,parseFloat:Re,postMessage:Fe,dispatchEvent:$e,addEventListener:Ve,removeEventListener:qe,alert:Be,prompt:Xe,confirm:He,close:Je}),w_w:ct({console:e=>{const t=ct({});let n=!1;return wt(i(e),o=>{const r=pt(e,o);r&&(lt(t,o,r),n=!0)}),n?t:void 0},FileReader:!0,DOMParser:!0,ReadableStream:!0,XMLHttpRequest:!0,JSON:!0,Math:!0,Date:!0,Event:!0,CustomEvent:!0,KeyboardEvent:!0,MouseEvent:!0,MutationEvent:!0,Error:!0,
Uint8Array:!0,Promise:!0,Object:!0,Blob:!0,Array:!0,Number:!0,String:!0}),d_b:ct({getElementById:We,createEvent:Ke,createElement:Ye,dispatchEvent:$e,addEventListener:Ve,removeEventListener:qe})})},(e,t,n)=>{const{cSO:o,sOP:r,gOP:s,gOPV:a,tT:i,w_o:{Proxy:c,Number:l},f:{A_f:d,A_c:u,A_fE:p,F_b:m,O_a:g,O_k:f,O_gPO:_,O_dPy:v,O_gOPD:h,O_gOPDs:b,N_MSI:w,M_f:y,S_su:M,Y_tST:E,F_a:S}}=e,L=(e=>{let t=o({});const n=(e,o,r)=>{const s=_(e);s&&s===o||(null!=s&&--r>=0&&n(s,e,r),t=g(t,b(e)))};return n(e,null,5),
t})(t);return o({createProxy:e=>{let _=L;const x=e=>{let t,n;const r=(t=h(P,e))||(n=_[e]);return o({d:r,l:!!t,w:!!n})},O=e=>{if(!T(e))return!1;if("length"===e)return!0;const t=y(l(e));return t>=0&&t<=w&&e===""+t},C=e=>"on"===M(e,0,2),T=e=>"string"==typeof e,R=(e,t)=>{const o=M(e,2),r=A[o];if(r&&(n.removeEventListener(o,r),delete A[o]),t&&(e=>"function"==typeof e)(t)){const e=(...e)=>S(t,n,e);n.addEventListener(o,e),A[o]=e}},U=o({addEventListener:!0,alert:!0,atob:!0,blur:!0,btoa:!0,
cancelAnimationFrame:!0,cancelIdleCallback:!0,captureEvents:!0,clearInterval:!0,clearTimeout:!0,close:!0,confirm:!0,createImageBitmap:!0,dispatchEvent:!0,dump:!0,fetch:!0,find:!0,focus:!0,getComputedStyle:!0,getDefaultComputedStyle:!0,getSelection:!0,matchMedia:!0,moveBy:!0,moveTo:!0,open:!0,openDatabase:!0,postMessage:!0,print:!0,prompt:!0,queueMicrotask:!0,releaseEvents:!0,removeEventListener:!0,requestAnimationFrame:!0,requestIdleCallback:!0,resizeBy:!0,resizeTo:!0,scroll:!0,scrollBy:!0,
scrollByLines:!0,scrollByPages:!0,scrollTo:!0,setInterval:!0,setResizable:!0,setTimeout:!0,sizeToContent:!0,stop:!0,updateCommands:!0,webkitCancelAnimationFrame:!0,webkitRequestAnimationFrame:!0,webkitRequestFileSystem:!0,webkitResolveLocalFileSystemURL:!0});p(f(U),t=>{e[t]=e[t]||o({bind:!0})});const A=o({}),P=o({});r(P,E,"Window");const D=new c(P,o({defineProperty:(n,r,s)=>{const{d:a,l:i}=x(r),c=o(s)
;return a&&!a.configurable&&(!!a.configurable!=!!c.configurable||!!a.enumerable!=!!a.enumerable)||O(r)?(v(i?P:t,r,c),!1):(v(P,r,c),T(r)&&C(r)&&R(r),delete e[r],!0)},deleteProperty:(t,n)=>{let{d:r,l:s,w:a}=x(n);return!(!r||!r.configurable)&&(s&&(s=delete P[n],T(n)&&C(n)&&R(n)),(a||(r=_[n])&&r.configurable)&&(L===_&&(_=g(o({}),L)),a=delete _[n]),delete e[n],s||a)},get:(n,r)=>{const a=e[r];if(a){if("value"in a)return a.value;if(a.get)return a.get()}const{d:i,l:c}=O(r)?o({d:h(t,r),l:!1}):x(r);if(i){
let e;const n="value"in i?s(i,"value"):(e=s(i,"get"))&&"function"==typeof e?c?e():m(e,t)():void 0;return a&&a.bind?m(n,t):c||"event"==r?n:n===t||"globalThis"===r?D:n}},getOwnPropertyDescriptor:(n,r)=>{let{d:s,l:a}=x(r);if(!s){const n=e[r];if(n)return o({enumerable:!0,configurable:!0,writable:!0,value:n.value,set:n.set,get:n.get});if(!O(r))return;s=h(t,r),a=!1}const i=g(o({}),s);if(i.value===t&&(i.value=D),!a){const e=i.get;e&&(i.get=()=>{const n=m(e,t)();return n===t?D:n}),
i&&!i.configurable&&v(P,r,i)}return i},has:(t,n)=>n in P||n in e||n in _,ownKeys:()=>{const e=e=>!(e in _),n=f(_),r=d(f(b(P)),e),s=o({});for(let e=0;"Window"===i(a(t,e));e+=1)s[e]=!0;const c=d(f(s),e);return u(n,r,c)},preventExtensions:()=>!0,set:(t,n,o)=>{const a=e[n];if(a&&a.set)return a.set(o),!0;const{d:i}=x(n);return!(i&&!i.writable&&!s(i,"set")||O(n)||(delete e[n],r(P,n,o),T(n)&&C(n)&&R(n,o),0))}}));return D}})}],backup:(e,t,n,o,r,s,a)=>{const i=e[n],c=e.document,l=s(i||r(e),e)
;i&&delete e[n];const{c_e:d,c_w:u,F_a:p,A_c:m,A_fE:g,J_ss:f,J_p:_,O_k:v,O_dPy:h,M_i:b,M_pA:w,M_r:y,N_tS:M,D_cS:E,E_r:S,M_aN:L,M_rN:x,C_d:O}=l.f,{cSO:C,pO:T,gOP:R,gOPV:U,sOP:A,tT:P}=l,D=C({...l.w,...l.w_o}),I=C({}),k=C({});g(v(l.w_w),async t=>{if(!I[t])try{const n=U(e,t);if(void 0===n)return;const o=l.w_w[t];I[t]="function"==typeof o?o(n):n}catch(e){u(e)}});const N=U,G=C({createID:()=>M(y()+1,36),arrayGet:N}),j=(e,t)=>{
if((d||console.error)(`Tampermonkey sandbox preparation ${t?"("+t+") ":""}failed. This usually is caused by a third-party extension.`,e),t)return()=>{}},F=e=>{g(v(l.d_b),t=>{try{const n=l.d_b[t];k[t]=function(){return p(n,e,arguments)}}catch(e){k[t]=j(e,"document."+t)}})},{createProxy:$}=a(l,e,D),V=e=>{B.send("csp",C({src:e}))},q=(t,n,o)=>{h(e,t,C({set:r=>{delete e[t];const s=E(c);return s&&S(s),p(r,n,o)},configurable:!0,enumerable:!1}))};let B,X=C({backup:l,safeWindow:D,sandboxWindow:I,
safeDocument:k,cSO:C,pO:T,gOPV:U,gOP:R,sOP:A,Context:C({D:o,Helper:G,cP:$,tT:P,cSD:F,pageLoaded:void 0,domContentLoaded:void 0,domLoaded:void 0,Message:void 0})});try{(()=>{const n=C({...l.f,E_u:function(t,n){return n?((t,n)=>{const o="__p__"+(19831206*y()+1);q(o,n,void 0),V('window["'+o+'"] = function(){'+t+"};"),delete e[o]})(t,n):V(t)}});g(v(n),e=>{try{X.Context[e]=n[e]}catch(t){X.Context[e]=j(t,"internal."+e)}}),g(v(l.w_f),t=>{try{const n=l.w_f[t];D[t]=I[t]=function(){return p(n,e,arguments)
}}catch(e){D[t]=I[t]=j(e,"window."+t)}}),g(["frames","self","top","document","location"],t=>{try{D[t]=I[t]=e[t]}catch(e){D[t]=I[t]=j(e,"window."+t)}}),F(t)})()}catch(e){return j(e)}try{B=(({CustomEvent:t,dispatchEvent:n,addEventListener:o,removeEventListener:r},{createEvent:s})=>{let a,i,c,l,d=1;const u=C({});let v=[];const h=e=>{const t=++d;return u[d]=e,t},y=(o,r)=>{const{m:a,a:i,r:c,n:l}=r,d=((e,n,o)=>{let r;return o?(r=s("MutationEvent"),b(r,e,!1,!1,o||null,null,null,f(n),w)):r=new t(e,C({
detail:n})),r})(o,C({m:a,a:i,r:c}),l);p(n,e,[d])};let M=e=>{const t=T("CustomEvent"==P(n=e)?O(n):_(L(n)));var n;if("message.response"==t.m)((e,t)=>{let n;e&&(n=u[e])&&(n(t),delete u[e])})(t.r,t.a);else if(a){const n=t.r?e=>{y(c,C({m:"message.response",a:e,r:t.r}))}:()=>{};!1===a(C({method:t.m,args:t.a,node:"MutationEvent"===P(e)?x(e):void 0,sendResponse:n}))&&(v=m(v,e))}};const E=t=>{t&&(l=t,c="2C_"+l,i="2P_"+l),p(o,e,[i,M,C({capture:!0})])},S=C({init:e=>{l?E():E(e)},switchId:e=>{l&&S.cleanup(),
E(e)},send:(...e)=>{let t,n,o,r;const s=N(e,0),a=N(e,1),i=N(e,2),l=N(e,3);"function"!=typeof i?(t=s,n=a,o=i,r=l):(t=s,n=a,r=i),y(c,C({m:t,a:n,r:r?h(r):null,n:o}))},onMessage:C({setListener:(e,t)=>{a=e,t||(g(v,e=>{M(e)}),v=null)}}),cleanup:()=>{i&&p(r,e,[i,M,!0]),i=null}});return S})(D,X.safeDocument),B.init(n),B.onMessage.setListener(({method:e,args:t})=>{
if(X)if("commid"==e)B.switchId(t.id);else if("load"==e)X.Context.pageLoaded=!0;else if("DOMContentLoaded"==e)X.Context.domContentLoaded=!0;else if("cleanup"==e)B.cleanup(),X=null;else{if("next"!=e)return!1;q(t.id,X)}},!0),X.Context.Message=B}catch(e){return j(e)}},
next:(e,t,n,o,r,s,a,i,c,l,d,u,p,m)=>["const backup = this;","(function TM_back() {","const { cSO, pO } = backup;","const Context = backup.Context = cSO(backup.Context);","const copy = function(src) {",'"use strict";',"const props = Context.O_gOPN(src);","for (let kk, ii=0; (kk=props[ii]) !== undefined; ii++) {","Context[kk] = src[kk];","};","};","copy(backup);","with (Context) {","(() => {",'"use strict";',"copy({","Context,",`V:!!${a},`,`ENV:!!${i},`,`TS:!!${l},`,`D:!!${d},`,`use:pO(${o}),`,`scripts:${t},`,"_content: false,",`flags:pO(${n}),`,`ScriptPermissionToGrant:pO(${r}),`,"write_listeners: [ d => {","Context.cSD(d);","Message.init();","} ]","});",'safeWindow.addEventListener("unload", evt => Message.cleanup(), cSO({ capture: false, once: true }));',(()=>{
let t="";a&&(t+="let V = true;"),c&&(t+="let EV = true;"),i&&(t+="let ENV = true;"),t+=`let logLevel = ${s};`;const n=`let contextId = "${e}";`;let o="";return u||"complete"==document.readyState?(o+="Context.pageLoaded |= true;",o+="Context.domContentLoaded |= true;"):(p||"interactive"==document.readyState)&&(o+="Context.domContentLoaded |= true;"),`${t+n+"const Event = function() {};const Window = function() {};Window.prototype = cSO({});"+o}(${m})(Context, contextId);\n`
})(),"})();","};","})();"].join(""),environment:function(e,t){
const n=e.V,o=e.EV,r=e.D,{pO:s,sOP:a,gOP:i,cP:c,tT:l,safeWindow:d,sandboxWindow:u,safeDocument:p,flags:m,ScriptPermissionToGrant:g,E_u:f,F_a:_,F_c:v,F_tS:h,A_fE:b,A_sl:w,A_sp:y,A_so:M,A_po:E,A_sh:S,A_j:L,A_f:x,A_iO:O,A_c:C,O_a:T,O_k:R,O_dP:U,O_dPy:A,O_gOPN:P,J_ss:D,J_n:I,c_l:k,c_w:N,c_e:G,c_d:j,M_f:F,M_r:$,M_m:V,P_r:q,P_t:B,P_c:X,S_fCC:H,S_sl:J,S_su:W,S_sp_nr:K,S_tr:Y,S_rA_nr:z,S_se_nr:Q,S_cCA:Z,S_tLC:ee,S_tUC:te,R_rABS:ne,R_rAT:oe,D_pFS:re,R_enq:se,R_cl:ae,X_o:ie,X_pSD:ce,X_pSH:le,X_pSL:de,X_pSO:ue,X_pSU:pe,X_s:me,M_pA:ge,M_pAT:fe,D_n:_e}=e,ve=e.Message,he=e.cSO,{createID:be,arrayGet:we}=e.Helper,ye=(e,t,n,o)=>{
const r=Q(e,t);if(-1==r)return;const s=W(e,r+t.length);if(!n)return s;const a=Q(s,n);return-1==a?o&&o.optionalEnd?s:void 0:W(e,r+t.length,a)},Me=window,Ee=Me.document,Se="DOMContentLoaded",Le="load",xe="DOMNodeInserted";e.domContentLoaded=e.domContentLoaded||!1,e.pageLoaded=e.pageLoaded||!1,e.domNodeInserted=e.domNodeInserted||!1,e.props=he({});const Oe=(()=>{let e=0,t=0;const n=he({}),o=he({}),r=function(e,t,o,r){const s=this,a=()=>{n[o]&&(_(e,s,r),delete n[o])}
;if("function"==typeof e)if(n[o]=e,0===t){const e=q();B(e,()=>a())}else ve.send("setTimeout",he({t:t||1}),()=>a())},s=function(e,t,n,r){const s=this;if("function"==typeof e){const i=o[n]=Re.connect("setInterval");i.onMessage.addListener(()=>{o[n]&&_(e,s,r)}),i.onDisconnect.addListener(()=>{a(n)}),i.postMessage(he({method:"setInterval",t:t||1}))}},a=e=>{const t=o[e];t&&(t.disconnect(),delete o[e])},i=he({setTimeout:(e,t,...n)=>{const o=be();return r(e,t,o,n),o},
clearTimeout:e=>(e=>delete n[e])(e),setInterval:(e,t,...n)=>{const o=be();return s(e,t,o,n),o},clearInterval:e=>a(e)}),c=he({setTimeout:(e,n,...o)=>{const s=++t;return n=V(n,1),r(e,n,s,o),s},setInterval:(t,n,...o)=>{const r=++e;return n=V(n,1),s(t,n,r,o),r}});return b(R(i),e=>d[e]=i[e]),c})(),Ce=(()=>{let t=[];const n=e=>{e()},o=e=>{if(Ee.body)e&&(e(),e=null);else{const t=[Le,xe,Se],n=()=>{b(t,e=>{p.removeEventListener(e,n,!0)}),o(e)};b(t,e=>{p.addEventListener(e,n,!0)})}};var s=he({
runListeners:()=>{let e;for(;e=S(t);)e()},run:a=>{const{script:{name:i,options:c}}=a,l=()=>{Pe.create(a)};var u;"document-start"==c.run_at?(r&&j(`env: run "${i}" ASAP -> document-start`),n(l)):"document-body"==c.run_at?(r&&j(`env: schedule "${i}" for document-body`),o(l)):"context-menu"==c.run_at?(r&&j(`env: run "${i}" ASAP -> context-menu`),n(l)):"document-end"==c.run_at?(r&&j(`env: schedule "${i}" for document-end`),t=C(t,l),
e.domContentLoaded&&s.runListeners()):(r&&j(`env: schedule "${i}" for document-idle`),u=l,t=C(t,()=>{d.setTimeout(u,1)}),e.domContentLoaded&&s.runListeners())}});return s})();(n||r)&&j(`env: initialized (content, id:${W(t,0,10)}..., ${d.location.origin}${d.location.pathname}) `);const Te=he({UTF8:he({encode:e=>d.unescape(d.encodeURIComponent(e)),decode:e=>d.decodeURIComponent(d.escape(e))}),Base64:he({encode:e=>{let t="";for(let n=0;n<e.length;n++)t+=H(255&Z(e,n));return d.btoa(t)},
decode:e=>d.atob(e)}),str2abSync:e=>{const t=new d.Uint8Array(e.length);for(let n=0;n<e.length;n++)t[n]=Z(e,n);return t.buffer},ab2strSync:e=>{let t="";const n=new d.Uint8Array(e);for(let e=0;e<n.length;e+=32687)t+=_(H,null,n.subarray(e,e+32687));return t},blob2str:(e,t)=>new d.Promise(n=>{const o=new u.FileReader;o.onload=()=>{n(o.result)},o.onerror=e=>{N("unable to decode data "+e),n("")},t?oe(o,e,t):ne(o,e)})}),Re=(()=>{const e=he({});let t;const n=t=>{let n=[],o=[];const r=()=>{n=null,
o=null,s=null,delete e[t]};var s=he({postMessage:e=>{ve.send("port.message",he({response_id:t,value:e}))},onMessage:he({addListener:e=>{n=C(n,e)}}),onDisconnect:he({addListener:e=>{o=C(o,e)}}),disconnect:()=>{ve.send("port.message",he({response_id:t,disconnect:!0})),r()}});return e[t]=he({message:e=>{n&&b(n,t=>{t(e)})},disconnect:e=>{o&&b(o,t=>{t(e)}),r()}}),s};return he({message:o=>{let s;if(o.connect)t&&t(o.destination,n(o.response_id));else{
if(!(s=e[o.response_id]))return void(r&&N("ports: unknown id",o.response_id,o));o.disconnect?s.disconnect():s.message(o.value)}},connect:e=>{const t=be();return ve.send("port.message",he({response_id:t,connect:!0,destination:e})),n(t)},onConnect:he({addListener:e=>{t=e}})})})(),Ue=(()=>{const e=he({objs:he({}),push:(t,n)=>{0!==n&&1!==n&&(n=0);const o=F(19831206*$()+1);return e.objs[o]=he({fn:t,prio:n}),o},remove:t=>delete e.objs[t],get:t=>{let n=[];for(let o=0;o<=1;o++)b(R(e.objs),r=>{
e.objs[r].prio!==o||void 0!==t&&r!=t||(n=C(n,e.objs[r].fn))});return void 0===t?n:we(n,0)},finalize:t=>{if(void 0!==t){let n;return e.objs[t]&&(n=e.objs[t].fn(),delete e.objs[t]),n}{const t=e.get();for(let e=0;e<t.length;e++)t[e]()}}});return e})(),Ae=(()=>{const e=(e,n,o)=>{ve.send("setClipboard",he({content:e,info:n,id:t}),o?()=>o():null)},o=(e,t)=>M(t,t=>-1!=O(e,t)),i=he({});return he({syntaxCheck:(e,t)=>{ve.send("syntaxCheck",he({code:e}),t)},of:c=>{const f=c.script,v=(()=>{let e=[]
;const s=c.storage;let a=0;const i=o(f.grant,g.readValues),l=o(f.grant,g.writeValues),u=(e,t)=>{if("string"!=typeof e)return t;{const n=W(e,0,1);switch(e=W(e,1),n){case"b":return"true"===e;case"n":return d.Number(e);case"x":return Te.UTF8.decode(Te.Base64.decode(e));case"o":try{return I(e)}catch(e){k("values: parseValueFromStorage: "+e)}return t;case"u":return;default:return e}}},p=(t,n,o,s)=>{n!=o&&b(e,e=>{if(e&&e.key==t&&e.cb)try{e.cb(t,u(n),u(o),s)}catch(e){
r&&N(`values: change listener of "${t}" failed with: ${e.message}`)}})},m=e=>{_&&_.postMessage(he({method:"saveStorageKey",uuid:f.uuid,key:e,value:s.data[e],id:t,ts:s.ts}))};if(i){var _=Re.connect("values");_.onMessage.addListener(e=>{if(!e.storage)return;const t=e.storage.data;e.removed&&(t[e.removed]=void 0),b(R(t),e=>{const o=s.data[e],r=t[e];void 0===r?delete s.data[e]:s.data[e]=r,n&&k(`values: message - config key ${e}: ${o} -> ${r}`),p(e,o,r,!0)})}),_.onDisconnect.addListener(()=>{
r&&k("values: port disconnected"),_=null}),_.postMessage(he({method:"addStorageListener",uuid:f.uuid,id:t}))}return he({...he(i?{get:(e,t)=>u(s.data[e],t),list:()=>R(s.data),registerChangeListener:(t,n)=>{const o=++a,r=he({id:o,key:t,cb:n});return e=C(e,r),o},unregisterChangeListener:t=>{e=x(e,e=>e.id!==t)}}:{get:void 0,list:void 0,registerChangeListener:void 0,unregisterChangeListener:void 0}),...he(he(l?{set:(e,t)=>{const n=s.data[e];s.ts=_e(),s.data[e]=(e=>{let t=W(typeof e,0,1);switch(t){
case"o":try{e=t+D(e)}catch(e){return void k(e)}break;case"s":-1===Q(e,H(8232))&&-1===Q(e,H(8233))||(t="x",e=Te.Base64.encode(Te.UTF8.encode(e))),e=t+e;break;default:e=t+e}return e})(t),m(e),p(e,n,s.data[e],!1)},remove:e=>{const t=s.data[e];s.ts=_e(),delete s.data[e],m(e),p(e,t,s.data[e],!1)}}:{set:void 0,remove:void 0}))})})(),P=o(f.grant,g["window.onurlchange"])?(()=>{let e,n=[];return he({register:o=>{n=C(n,o),e||(e=Re.connect("onurlchange"),e.onMessage.addListener(({url:e})=>{e&&b(n,t=>t(he({
url:e})))}),e.postMessage(he({method:"observeUrlChanges",uuid:f.uuid,id:t})))},unregister:t=>{let o;t&&(o=O(n,t))>-1&&(n=y(n,o,1).result),e&&0===n.length&&(e.disconnect(),e=null)}})})():void 0,F=o(f.grant,g.getResource)?he({getText:e=>{for(let t=0;t<f.resources.length;t++){const n=f.resources[t];if(n.name==e){if(n.error)N("@resource: "+n.error);else try{if("string"==typeof n.content)return Te.UTF8.decode(n.content)}catch(e){}return""}}return null},getUrl:e=>{
for(let t=0;t<f.resources.length;t++){const n=f.resources[t];if(n.name==e){if(n.error)N("@resource: "+n.error);else if("string"==typeof n.content){try{return`data:${n.meta||"application/octet-stream"};base64,${Te.Base64.encode(n.content)}`}catch(e){}return n.url}return""}}return null}}):he({getUrl:void 0,getText:void 0}),$=o(f.grant,g.tabs)?he({set:(e,t)=>{ve.send("tabs",he({action:"set",uuid:f.uuid,tab:e}),t?()=>t():null)},get:e=>{ve.send("tabs",he({action:"get",uuid:f.uuid}),e?t=>{e(t||he({}))
}:null)},getAll:e=>{ve.send("tabs",he({action:"list",uuid:f.uuid}),e?t=>{e(t||he({}))}:null)}}):he({set:void 0,get:void 0,getAll:void 0}),V=o(f.grant,g.xmlHttpRequest)?(()=>{const e=e=>{const o=s(e);let r=!1,a=()=>{r=!0};const i=(e,t)=>{t=t||he({}),e&&d.setTimeout(()=>{T(t,n),_(e,t,[t])},1)};"object"==typeof o.url&&o.url.href&&(o.url=o.url.href);const c=(e,t)=>{let n,o,r=l(e);if("Blob"===r||"File"===r){const n=e;B(Te.blob2str(n),e=>{t(he({type:r,value:e,meta:n.type,name:n.name,
lastModified:n.lastModified}))})}else if("FormData"===r){const r=e,s=r.keys();let a;const i=he({});for(n=[];!(a=s.next()).done;)n=C(n,a.value);o=()=>{if(n.length){const e=E(n);let t=r.getAll(e);"[]"!==W(e,-2)&&(t=we(t,0)),c(t,t=>{i[e]=t,o()})}else t(he({type:"FormData",value:i}))},o()}else if("Array"===r||"Object"===r){const s=e;let a,i,l=0,u=0;"Object"===r?(n=R(s),i=e=>e<n.length?n[e]:null,a=he({})):(i=e=>e<s.length?e:null,a=[]),o=()=>{const e=i(l);null===e?t(he({type:r,value:a})):c(s[e],t=>{
a[e]=t,l++,u++<1024?o():(u=0,d.setTimeout(o,1))})},o()}else t(he({value:e}))},p=(e,t,n,o,r)=>{let s;if(n)"stream"==o&&(s=n);else if("arraybuffer"==o)s=t||Te.str2abSync(e);else if("blob"==o)s=new u.Blob([t||Te.str2abSync(e)],he({type:r}));else if("json"==o)s=I(e);else{if("document"==o){const t=new u.DOMParser,n=we(K(r||"text/xml",";"),0);return re(t,e,n)}s=e||(t?Te.ab2strSync(t):"")}return s};return(e=>{if(o.url){const t=W(o.url,0,5);if(-1!=O(["data:","blob:"],t))return e()}if(!o.data)return e()
;c(o.data,t=>{o.binary&&(t.type="Blob"),o.data=t,o.data_type="typified",e()})})(()=>{if(r)return r=!1,void i(o.onabort);let e,n,s,c=Re.connect("xhr"),l=[];const{method:m,url:g,headers:_,cookie:v,binary:h,nocache:y,revalidate:E,timeout:T,context:U,responseType:P,overrideMimeType:D,anonymous:I,fetch:k,user:j,password:F,data:$,data_type:V}=o,q=he({method:m,url:g,headers:_,cookie:v,binary:h,nocache:y,revalidate:E,timeout:T,responseType:P,overrideMimeType:D,anonymous:I,fetch:k,user:j,password:F,
data:$,data_type:V});let B,X,H,J;q.headers&&b(R(q.headers),e=>{"cookie"===ee(e)&&(q.cookie=d.String(q.headers[e]),delete q.headers[e])}),c.postMessage(he({method:"xhr",details:q,callbacks:he({onloadstart:!!o.onloadstart,onload:!!o.onload,ondone:!!o.onloadend,onreadystatechange:!!o.onreadystatechange,onerror:!0,onabort:!!o.onabort,ontimeout:!!o.ontimeout,onprogress:!!o.onprogress,onpartial:!0}),id:t,url:d.location.href,uuid:f.uuid}));const W=P?ee(P):"";let z;const Q=async t=>{
if(t&&(s||void 0!==e||void 0!==n)){if(D?J=D:t&&(J=(e=>{const t=he({});return e&&b(K(e,"\n"),e=>{const n=K(e,":");if(n.length<2)return;const o=we(n,0);if(!o)return;const r=L(w(n,1),":");t[ee(Y(o))]=Y(r||"")}),t})(t.responseHeaders)["content-type"]),B=e,s)H=s.stream;else if(n){const e=n;if(X=e.buffer,-1==O(["blob","arraybuffer"],W)&&!B){let t;M([J,e.type],e=>t=ye(ee(e||""),"charset=",";",he({optionalEnd:!0})));const n=new d.Blob([X]);z=Te.blob2str(n,t),B=await z}z=void 0}else z&&await z;e=n=void 0
}if(B||H||X){t.responseType=P,b(["response_data"],e=>{delete t[e]});const e=he({response:()=>p(B,X,H,W,J||"binary/octet-stream"),responseText:()=>p(B,X,H,"text",J),responseXML:()=>p(B,X,H,"document","text/xml")});b(R(e),n=>{A(t,n,he({get(){try{return e[n]()}catch(e){N(m+":",e)}}}))})}};let Z=[];const te=async e=>{e&&(Z=C(Z,e));{const e=S(Z);e&&e()}};"stream"===W&&te(async()=>{s=await new d.Promise(e=>{const t=new u.ReadableStream(he({start:n=>{d.setTimeout(()=>e(he({stream:t,ctrl:n})),0)}}))})
}),c.onMessage.addListener(t=>te(()=>(async t=>{if(t.data&&U&&(t.data.context=U),t.onload)await Q(t.data),i(o.onreadystatechange,t.data),i(o.onload,t.data);else if(t.onreadystatechange)await Q(t.data),4!=t.data.readyState&&i(o.onreadystatechange,t.data);else if(t.onpartial){const o=t.data;if(s){const e=se||((e,t)=>e.enqueue(t));if(void 0!==o.partial)e(s.ctrl,o.partial);else if(void 0!==o.nada){const t=new d.Uint8Array(o.nada.buffer);e(s.ctrl,t)}else G(m+":","data message without data?!")}else{
let t;o.partial&&(l=C(l,o.partial)),o.nada&&(t=o.nada),void 0!==o.index&&o.index!==o.length-1||(l.length&&(e=L(l,""),l=[]),n=t)}}else if(t.onerror)t.exception&&G(t.exception),i(o.onerror,t.data);else if(t.onabort)i(o.onabort,t.data);else if(t.ondone)s&&(ae||(e=>e.close()))(s.ctrl),await Q(t.data),i(o.onloadend,t.data);else if(t.onloadstart)s&&await Q(t.data),i(o.onloadstart,t.data);else{const e=we(x(["onprogress","ontimeout"],e=>!!t[e]),0)||"onerror";i(o[e],t.data)}})(t))),
c.onDisconnect.addListener(()=>c=null),a=()=>{c&&c.postMessage(he({cancel:!0}))}}),he({abort:()=>{a()}})},n=(()=>{const e=he({DONE:ce,HEADERS_RECEIVED:le,LOADING:de,OPENED:ue,UNSENT:pe});return b(["text","arraybuffer","blob","document","json","stream"],t=>{e["RESPONSE_TYPE_"+te(t)]=t}),e})();return b(R(n),t=>a(e,t,n[t])),e})():void 0,q=o(f.grant,g.notification)?e=>{const{text:n,title:o,image:r,highlight:a,silent:i,timeout:c,onclick:l,ondone:d}=s(e),u=he({id:t,uuid:f.uuid,text:n,title:o,image:r,
highlight:a,silent:i,timeout:c});n||a?ve.send("notification",u,e=>{l&&e.clicked&&l(),d&&d(!0===e.clicked)}):N("GM_notification: neither a message text nor highlight options were given!")}:void 0;let X,J;const z=o(f.grant,g.webRequest)?(e,t)=>{const n=()=>{J==o&&(J=null),o=null};J&&J.disconnect();var o=J=Re.connect("webRequest");return t&&o.onMessage.addListener(e=>{t(e.type,e.message||"ok",e.details)}),o.onDisconnect.addListener(n),o.postMessage(he({rules:e,uuid:f.uuid})),he({abort:()=>{
o&&o.disconnect(),n()}})}:void 0,Z=o(f.grant,g.menuCommand)?(()=>{let e=0;const t=he({}),o=he({register:(r,s,a)=>{const i="registerMenuCommand",c=++e,l=Re.connect(i);return l.onMessage.addListener(e=>{if("run"===e.method){const t=e.event,n=t?t.keyCode?new d.KeyboardEvent("keypress",t):new d.MouseEvent("click",e.event):void 0;d.setTimeout(()=>s(n),1)}}),l.onDisconnect.addListener(()=>{o.unregister(c)}),l.postMessage(he({method:"register",name:r,uuid:f.uuid,accessKey:a})),
n&&k(`env: ${i} ${h(s)}`),t[c]=l.disconnect,c},unregister:e=>{let o;n&&k("env: unregisterMenuCommand "+e),(o=t[e])&&(o(),delete t[e])}});return o})():he({register:void 0,unregister:void 0}),ne=o(f.grant,g.cookie)?(()=>{const e=(e,t)=>he({action:e,uuid:f.uuid,url:d.location.href,details:t});return he({set:(t,n)=>{ve.send("cookie",e("set",t),n?e=>{n(e.error)}:null)},delete:(t,n)=>{ve.send("cookie",e("delete",t),n?e=>{n(e.error)}:null)},list:(t,n)=>{ve.send("cookie",e("list",t),n?e=>{
n(e.cookies,e.error)}:null)}})})():void 0,oe=({root:e,tag:t,properties:n,cb:o})=>{const r=be(),s=he({tag:t,properties:n,id:r,uuid:f.uuid});return ve.send("addElement",s,e,o?()=>o():null),p.getElementById(r)},ge={getInfo:()=>{if(!X){const{script:e,header:t,code:n}=c,{updateURL:o,fileURL:r,grant:s,options:{run_at:a,override:{orig_excludes:i,orig_includes:l,orig_matches:d}}}=e,{version:u,inIncognitoContext:p,isFirstPartyIsolation:g,downloadMode:f}=m,_=he({id:1,enabled:1,hash:1,fileURL:1
}),v=o||r,h=he({unwrap:!1,"run-at":a,excludes:i,includes:l,matches:d,grant:s}),w=he({scriptMetaStr:t,scriptSource:n,scriptWillUpdate:!!v,scriptUpdateURL:v,version:u,scriptHandler:"Tampermonkey",isIncognito:p,isFirstPartyIsolation:g,downloadMode:f,script:h});b(R(e),t=>{_[t]||(h[t]=e[t])}),X=w}return I(D(X))},registerMenuCommand:Z.register,unregisterMenuCommand:Z.unregister,webRequest:z,openInTab:(e,t)=>{let n,o=null,s=!1,a=null;const i=(()=>{let e=[];return he({run:t=>{if(t&&(e=C(e,t)),
o)for(;e.length;)E(e)()}})})();let c=Re.connect("openInTab");const l=()=>{c&&c.postMessage(he({close:!0}))};c.onMessage.addListener(e=>{e.tabId?s?l():(o=e.tabId,i.run()):e.name?n=e.name:e.closed&&(s=!0,a&&(a(),a=void 0))}),c.onDisconnect.addListener(()=>{c=null}),c.postMessage(he({method:"openTab",url:e,options:t,uuid:f.uuid}));const d=he({});return U(d,he({close:he({value:()=>{s?r&&j("env: attempt to close already closed tab!"):l()}}),focus:he({value:()=>{c&&c.postMessage(he({focus:!0}))}}),
closed:he({get:()=>s}),onclose:he({get:()=>a,set:e=>{a=e}}),name:he({get:()=>n,set:e=>{i.run(()=>{c&&c.postMessage(he({name:e}))})}})})),d},setValue:v.set,getValue:v.get,deleteValue:v.remove,listValues:v.list,urlChange:P,addValueChangeListener:v.registerChangeListener,removeValueChangeListener:v.unregisterChangeListener,getResourceText:F.getText,getResourceURL:F.getUrl,notification:q,xmlhttpRequest:V,cookie:ne,setTab:$.set,getTab:$.get,getTabs:$.getAll,log:o(f.grant,g.log)?function(){
_(k,this,arguments)}:void 0,download:o(f.grant,g.download)?(...e)=>{const t=we(e,0),n="Object"===l(t)?t:he({url:t,name:we(e,1)}),o=(e,t)=>{t=t||he({}),e&&d.setTimeout(()=>{_(e,t,[t])},1)};let{url:r}=n;const{name:s,headers:a,saveAs:i}=n;let c=Re.connect("download");return c.onMessage.addListener(e=>{try{e.load?n.onload&&o(n.onload,e.data):e.progress?n.onprogress&&o(n.onprogress,e.data):e.timeout?n.ontimeout&&o(n.ontimeout,e.data):n.onerror&&o(n.onerror,e.data)}catch(e){
k("env: Error: TM_download - ",e,n)}}),c.onDisconnect.addListener(()=>{c=null}),(e=>{const t=()=>{e&&(e(),e=null)};if(m.blob_download_supported||"blob:"!==W(r,0,5))t();else{const e=new u.XMLHttpRequest;ie(e,"GET",r),e.responseType="blob",e.onload=()=>{4==e.readyState&&B(Te.blob2str(e.response),e=>{try{r="data:application/octet-stream;base64,"+Te.Base64.encode(e)}catch(e){N("env: Error: TM_download - ",e,n)}t()})},e.onerror=e.ontimeout=()=>{t()},me(e)}})(()=>{c&&c.postMessage(he({details:he({
url:r,name:s,headers:a,saveAs:i}),uuid:f.uuid}))}),he({abort:()=>{c&&c.postMessage(he({cancel:!0}))}})}:void 0,setClipboard:o(f.grant,g.setClipboard)?e:void 0,addStyle:o(f.grant,g.addElement)?(e,t)=>oe(he({root:void 0,tag:"style",properties:he({textContent:e}),cb:t})):void 0,addElement:o(f.grant,g.addElement)?(...e)=>{let t,n,o,r;const s=we(e,0),a=we(e,1),i=we(e,2),c=we(e,3);return"string"==typeof s?(n=s,o=a,r=i):(t=s,n=a,o=i,r=c),oe(he({root:t,tag:n,properties:o,cb:r}))}:void 0,
closeTab:o(f.grant,g["window.close"])?e=>{ve.send("closeTab",he({uuid:f.uuid}),e?()=>e():null)}:void 0,focusTab:o(f.grant,g["window.focus"])?e=>{ve.send("focusTab",he({uuid:f.uuid}),e?()=>e():null)}:void 0};return i[c.script.uuid]=i[c.script.uuid]||he(ge),i[c.script.uuid]}})})();var Pe=(()=>{const t=(e,t,n,o,r)=>{const s=t[n],a=typeof s;return o&&"string"===a?t[n]=()=>f(s,r):r&&"function"===a&&(t[n]=function(){return _(s,r,arguments)}),_(e,Me,t)},s=(e,t,n,o)=>{const r=he({attrChange:0,
attrName:null,bubbles:!0,cancelBubble:!1,cancelable:!1,clipboardData:void 0,currentTarget:null,defaultPrevented:!1,eventPhase:0,newValue:null,prevValue:null,relatedNode:null,returnValue:!0,srcElement:null,target:null,timeStamp:_e()}),s="string"==typeof n?()=>f(n,o):n,i=new Event(e);b(R(r),e=>{a(i,e,r[e])}),b(R(t),e=>{a(i,e,t[e])}),_(s,o,[i])},p=(e,t,r)=>{(n||o)&&k("env: postLoadEvent!");const a=he({attrName:"null",newValue:"null",prevValue:"null",eventPhase:fe,attrChange:ge,target:r=r||Ee,
relatedNode:r,srcElement:r});s(Le,a,e,t)},g=(e,t,r)=>{(n||o)&&k("env: postDomEventListener!");const a=he({attrName:"null",newValue:"null",prevValue:"null",eventPhase:fe,attrChange:ge,target:r=r||Ee,relatedNode:r,srcElement:r});s(Se,a,e,t)},h=(e,t)=>(void 0===t&&(t=100),t&&e&&(e==Ee||h(e.parentNode,t-1))),M=(()=>{let t=null;return n=>{t||(t=he({instance:n,is_open:!1}),b(["write","writeln","open","close"],o=>{t[o]=n[o],n[o]=function(){let r=!1
;-1!=O(["write","writeln","open"],o)?t.is_open?r=!0:t.is_open=!0:"close"===o&&(t.is_open=!1),!r&&t.is_open&&ve.send("document.write");const s=Ee.documentElement,a=_(t[o],n,arguments);if(!r&&t.is_open)return s!==Ee.documentElement&&(t.instance!==n&&(t=null,M(Ee)),b(e.write_listeners,e=>{e(Ee)})),a}}))}})(),E=he({});let x=[],T=[];const I=(s,i,c)=>{let l,u;const m=()=>{try{null.getSafeError}catch(e){u=e.constructor}return u};if(b(T,e=>{e.object===s&&(l=!0)}),!l){const l=he({object:s,
addEventListener:s.addEventListener,removeEventListener:s.removeEventListener});T=C(T,l);let f=[];const h=e=>{for(let t=0;t<f.length;t++)if(f[t].fn===e)return t};s.removeEventListener=function(e,t,n){const o=n&&"boolean"!=typeof n?!!n.capture:!!n;let r,s,a;if(void 0===(r=h(t))||!(s=f[r].listeners))return _(l.removeEventListener,this,arguments);(a=s[`${e}-${o}`])&&(_(l.removeEventListener,this,[e,a,n]),delete s[`${e}-${o}`]),P(s).length||(f=y(f,r,1).result)};const w=(e,t,n,o)=>{
const r=o&&"boolean"!=typeof o?!!o.capture:!!o;if(t){let o=x.length;const s=d.parseInt(L([n==Se?1:2,r?1:2,r?t:3-t,_e()],"0"));for(let e=0;e<x.length;e++){const t=x[e];if(!t||!t.prio||t.prio>s){o=e;break}}x=y(x,o,0,he({prio:s,fn:e})).result}else x=C(x,he({fn:e}))};s.addEventListener=function(s,a,b){(n||o)&&k("env: addEventListener "+s);const y=this;if(a&&(1==i&&s==Le||s==Se||s==xe)){const n=b&&"boolean"!=typeof b?!!b.capture:!!b;let o,M;try{let e=(u||m())();const t=e.stack||e.stacktrace;if(t){
const e=K(t,"\n");for(let t,n=0;n<e.length&&(!(t=ye(we(e,n),"tms_","\\$"))||!(o=E["tms_"+t]));n++);}}catch(e){r&&G("env: Error: event "+s,e)}if(o&&"document-idle"!==o.run_at){let t=null;if(s==Le?e.pageLoaded&&(t=()=>{o.load_fired=!0,p(a,y,y.document||y)},w(t,i,s,b)):s==Se&&e.domContentLoaded&&!o.load_fired&&(t=()=>{g(a,y,y.document||y)},w(t,i,s,b)),t){const e=()=>{if(x.length){const e=S(x);e&&e.fn&&e.fn()}};return void d.setTimeout(e,1)}}const L=function(e){return t(v,[a,this,c(e)],0,!0,y)}
;return void 0===(M=h(a))&&(M=f.length,f=C(f,he({fn:a,listeners:he({})}))),f[M].listeners[`${s}-${n}`]=L,_(l.addEventListener,y,[s,L,b])}return _(l.addEventListener,y,arguments)};try{const e=()=>"[native code]";b([s.addEventListener,s.removeEventListener],t=>{a(t,"toString",e)})}catch(e){}}},N=e=>{e.__evaluate||(U(e,he({__evaluate:he({value:e.evaluate,enumerable:!1,configurable:!1})})),e.evaluate=function(e,t,o,r,s){let a;if(n&&k("env: document.evaluate "+e),t||(t=this),
"undefined"!=typeof XPathResult){let i=e,c=null;try{a=this.__evaluate(i,t,o,r,s)}catch(e){c=e}let l,d=!1;try{d=d||!!a.snapshotLength}catch(e){}try{d=d||!!a.singleNodeValue}catch(e){}if(d||"."==(l=W(e,0,1))||h(t))n&&k("env: queried document for "+i);else{n&&k("env: query added elem for "+i),i=("/"==l?".":"./")+e;try{a=this.__evaluate(i,t,o,r,s)}catch(e){}}if(n&&k("env: query returned ",a,c),!d&&c)throw c}else n&&k("env: XPathResult == undefined, but selectNodes via ",e),a=t.selectNodes(e)
;return a},Ue.push(()=>{e.evaluate=e.__evaluate}))};return he({create:o=>{const s=o.script,p=he({}),g=-1!==O(s.grant,"none"),v=`${s.namespace}_${g}`;void 0===e.props[v]&&(e.props[v]=he({sandboxes:he({}),elements:he({})}),Ue.push(()=>{e.props[v]=null})),p.CDATA=he({value:function(e){this.src=e,this.toString=function(){return this.src},this.toXMLString=this.toString}}),p.uneval=he({value:e=>{try{return`\\$1 = ${D(e)};`}catch(e){k(e)}}}),p.define=he({value:void 0}),p.module=he({value:void 0}),
p.exports=he({value:void 0});const h=he({}),y=he({}),S=he({}),x=he({}),T=Ae.of(o);if(g);else{p.window=he({value:"context",overwrite:!0}),p.globalThis=he({value:"context",overwrite:!0}),p.unsafeWindow=he({value:Me}),p.cloneInto=he({value:e=>e}),p.exportFunction=he({value:(e,t,n)=>(n&&void 0!==n.defineAs&&(t[n.defineAs]=e),e)}),p.createObjectIn=he({value:(e,t)=>{const n=he({});return t&&void 0!==t.defineAs&&(e[t.defineAs]=n),n}}),h.addStyle=T.addStyle,h.addElement=T.addElement,
h.deleteValue=T.deleteValue,h.listValues=T.listValues,h.getValue=T.getValue,h.setValue=T.setValue,h.log=T.log,h.registerMenuCommand=T.registerMenuCommand,h.unregisterMenuCommand=T.unregisterMenuCommand,h.openInTab=T.openInTab,h.addValueChangeListener=T.addValueChangeListener,h.removeValueChangeListener=T.removeValueChangeListener,x.xmlhttpRequest=T.xmlhttpRequest,x.download=T.download,h.webRequest=T.webRequest,y.getTab=T.getTab,h.setTab=T.setTab,h.saveTab=T.setTab,y.getTabs=T.getTabs,
h.getResourceText=T.getResourceText,x.getResourceURL=T.getResourceURL,y.setClipboard=T.setClipboard?he({cb:2,fn:T.setClipboard}):void 0;const e=e=>function(){const t=q(_(e,this,arguments));return a(t,"then",e=>B(t,e)),a(t,"catch",e=>X(t,e)),t},t=(e,t)=>{let n;const o=new d.Promise((o,r)=>{const s=he({}),a=t.onload,i=t.ontimeout,c=t.onerror;b(R(t),e=>{s[e]=t[e]}),s.onerror=function(e){r(e),c&&_(c,this,arguments)},s.ontimeout=function(e){r(e),i&&_(i,this,arguments)},s.onload=function(e){o(e),
a&&_(a,this,arguments)};const l=e(s).abort;!0===n?l():n=l});return a(o,"abort",()=>{n?n():n=!0}),o};b(R(x),e=>{const t=x[e];void 0!==t&&(S["GM_"+e]=he({value:t}))}),b(R(y),e=>{const t=y[e];void 0!==t&&(S["GM_"+e]=he({value:t.fn||t}),S["GM."+e]=he({value:function(){let e,n=[];if(void 0===t.cb)e=t;else{e=t.fn;for(let e=0;e<t.cb;e++)n=C(n,arguments[e]||void 0)}return new d.Promise(t=>{_(e,this,C(n,[t]))})}}))}),b(R(h),t=>{const n=h[t];void 0!==n&&(S["GM_"+t]=he({value:n}),S["GM."+t]=he({
getter:()=>e(n)}))}),S["GM.getResourceUrl"]=x.getResourceURL?he({getter:()=>e(x.getResourceURL)}):void 0,S["GM.xmlHttpRequest"]=x.xmlhttpRequest?he({value:(()=>{const e=e=>t(x.xmlhttpRequest,e);return b(R(x.xmlhttpRequest),t=>a(e,t,x.xmlhttpRequest[t])),e})()}):void 0,S["GM.download"]=x.download?he({value:e=>t(x.download,e)}):void 0;const n=T.notification?(e,t,n,o)=>{let r=null,a=null;const i=he({});"object"==typeof e&&(a=e),a?(b(["timeout","text","image","title","highlight","silent"],e=>{
i[e]=a[e]}),r=a.ondone,o=a.onclick,"function"==typeof t&&(r=t)):(i.image=n,i.text=e,i.title=t),i.text&&(i.image=i.image||s.icon64||s.icon,i.title=i.title||s.name),i.onclick=o,i.ondone=r,T.notification(i)}:void 0;S.GM_notification=n?he({value:n}):void 0,S["GM.notification"]=n?he({value:(e,t,o,r)=>{let s;return s="object"==typeof e?e:he({text:e,title:t,image:o,onclick:r}),new d.Promise(e=>{let t=he({});b(R(s),e=>{t[e]=s[e]});const o=t.ondone;t.ondone=function(...t){o&&_(o,this,t),_(e,this,t)},n(t)
})}}):void 0,S.GM_cookie=T.cookie?he({value:(()=>{const e=T.cookie,t=(t,n,o)=>(e[t]||(()=>{}))(n,o);return b(R(e),n=>{a(t,n,e[n])}),t})()}):void 0,S["GM.cookie"]=T.cookie?he({value:(()=>{const e=T.cookie,t=he({});return b(R(e),e=>{t[e]=t=>((e,t)=>new d.Promise((n,o)=>{"list"==e?S.GM_cookie.value[e](t,(e,t)=>{t?o(t):n(e)}):S.GM_cookie.value[e](t,e=>{e?o(e):n()})}))(e,t)}),t})()}):void 0}S.GM_info=S["GM.info"]=T.getInfo?he({getter:T.getInfo}):void 0;const P=he({});var F,$,V,H;p.GM=he({value:P,
protect:!0}),F=p,$=s.grant,V=S,void 0===(H=(e,t)=>{if("GM."!==W(e,0,3))return t.protect=!0,t;e=we(K(e,"."),1),A(P,e,he({get:t.getter?t.getter:()=>t.value}))})&&(H=(e,t)=>t),b(C(["GM_info","GM.info"],$),e=>{let t;const n=V[e];n&&(t=H(e,n))&&(F[e]=t)}),s.options.compat_prototypes&&((n||r)&&k("env: option: add toSource"),i(u.Object.prototype,"toSource")||U(u.Object.prototype,he({toSource:he({value:function(){const e=l(this);if("String"===e)return`(String("${z(this,'"','\\"')}"))`
;if("Number"===e)return`(Number("${d.Number(this)}"))`;if("Array"===e){const e=this;let t="(new Array(";for(let n=0;n<e.length;n++){const o=e[n],r=l(o);t+="Null"===r?"null":"Undefined"===r?"undefined":e[n].toSource(),n+1<e.length&&(t+=",")}return t+="))",t}return`JSON.parse(unescape("${d.escape(D(this))}"))`},enumerable:!1,writable:!0,configurable:!0})})),(n||r)&&k("env: option: add some array generics"),b(["indexOf","lastIndexOf","filter","forEach","every","map","some","slice"],e=>{
if("function"!=typeof d.Array[e]){const t=he({});t[e]=he({value:function(t){return _(d.Array.prototype[e],t,w(arguments,1))},enumerable:!1,writable:!0,configurable:!0}),U(d.Array,t)}}));let Y,Q="";if(g)Y=he({});else{const e=(Z=T,ee=t=>{N(t),M(t),I(t,2,e.filterEvent)},(()=>{const e=function(e,n){if("urlchange"!=e||!Z.urlChange)return t(d.addEventListener,arguments,1,!0);Z.urlChange.register(n)},n=function(e,n){if("urlchange"!=e||!Z.urlChange)return t(d.removeEventListener,arguments,1,!0)
;Z.urlChange.unregister(n)},o=he({setTimeout:he({value:(...e)=>t(Oe.setTimeout,e,0,!0,s)}),setInterval:he({value:(...e)=>t(Oe.setInterval,e,0,!0,s)}),close:Z.closeTab?he({get:()=>d.self==d.top?e=>Z.closeTab(e):d.close}):void 0,focus:Z.focusTab?he({get:()=>e=>Z.focusTab(e)}):void 0,onurlchange:Z.urlChange?(r=null,he({get:()=>r,set:t=>{r&&n("urlchange",r),e("urlchange",r=t)}})):void 0,location:he({set:e=>{d.location.href=e}}),name:he({get:()=>Me.name,set:e=>{Me.name=e}}),document:he({get:()=>{
const e=d.document;return ee(e),e}}),clearInterval:he({get:()=>d.clearInterval}),clearTimeout:he({get:()=>d.clearTimeout}),addEventListener:he({value:e}),removeEventListener:he({value:n})});var r;b(R(u),e=>{const t=u[e];void 0!==t&&t!==Me&&(o[e]=o[e]||he({value:t}))});const s=c(o),a=he({context:s,filter:e=>e==Me?s:e,filterEvent:function(e){const t=he({});for(const n in e)if("function"==typeof e[n])t[n]=(()=>{const t=n;return function(){return _(e[t],e,arguments)}})();else{const o=a.filter(e[n])
;t[n]=o}return t}});return a})()),n=he({run_at:s.options.run_at,uuid:s.uuid});Q="tms_"+z(s.uuid,"-","_"),((e,t)=>{E[e]=t,d.addEventListener("load",()=>{d.setTimeout(()=>delete E[e],1)})})(Q,n),I(e.context,1,e.filterEvent),Y=e.context}var Z,ee;e.props[v].sandboxes[s.uuid]=Y,e.props[v].elements[s.uuid]=p,(n||r)&&j(`env: execute script ${s.name} @ the ${g?"un":""}safe context now!`),((e,t,n,o,s,i)=>{const{name:c}=e;let l=null
;const u=e=>z(z(e,'"','\\"'),"'","\\'"),p=()=>"[Tampermonkey property]",g=e=>{void 0!==e&&a(e,"toString",p)};try{const r=o.sandboxes[e.uuid],a=e.options.compat_powerful_this?r:he({});let d=["context","fapply"],p=["undefined","undefined"];const v=o.elements[e.uuid];let h;b(R(v),e=>{const t=v[e];t.overwrite?(d=C(d,e),p=C(p,t.value)):(d=C(d,e),p=C(p,"powers."+e),t.getter?A(a,e,he({get:()=>{const e=t.getter();return t.protect&&g(e),e}})):(t.protect&&g(t.value),a[e]=t.value))})
;const w=!e.options.unwrap
;l=L(w?["((context, powers, fapply) => {","with (context) {","(module => {",'"use strict";',"try {",m.measure_scripts?`console.time("${h=`SCRIPT RUN TIME[${u(c)}]`}");\n`:"","fapply(module, context, [",L(p,","),"]);",m.measure_scripts?`console.timeEnd("${h}");\n`:"","} catch (e) {","if (e.message && e.stack) {","console.error(\"ERROR: Execution of script '",u(c),"' failed! \" + e.message);","console.log(e.stack);","} else {","console.error(e);","}","}","})","("+(m.top_level_await?"async ":"")+"function ",s?s+"$":"","(",L(d,","),") {",m.enforce_strict_mode?'"use strict";\n':"",n,t,"\n","})","}","})(this.context, this.powers, this.fapply);\n",i?`//# sourceURL=${i}\n`:""]:[n,t,"\n",i?`//# sourceURL=${i}\n`:""],"")
;const y=he({context:r,powers:a,fapply:_});f(l,w?y:void 0)}catch(e){return void Ae.syntaxCheck(L([n,t],""),o=>{let s="";if(o.errors){const e=K(n,"\n").length-1;let t="";o.errors&&b(R(o.errors),n=>{const r=o.errors[n];if(r&&r.line>=0&&r.reason){const n=r.line;t+=L([n>e?"script:":"require:"," (",r.code,") ","."===W(r.reason,-1)?J(r.reason,0,-1):r.reason," on line: ",n>e?n-e:n," at character: ",r.character,"\n"],"")}}),s="Linter output:\n"+t}else s=t;const a=e.stack?e.stack:""
;r||o.errors?G(`Syntax error @ "${c}"!\n##########################\n${s}##########################\n\n${a}`):G(`Syntax error @ "${c}"!\n\n`,a),d.setTimeout(()=>{throw e},1)})}})(s,o.code,o.requires,e.props[v],Q,o.source_url)}})})();(()=>{if(!m.external_connect)return;let e;if(e=Me.external){const t=(e,t)=>{ve.send("external.message",e,t)};try{U(e,he({Tampermonkey:he({get:()=>he({getVersion:e=>{t(he({method:"getVersion"}),e)},openOptions:(e,n)=>{t(he({method:"openOptions",params:e}),n)},
isInstalled:(e,n,o)=>{"function"==typeof n&&(o=n,n=null),t(he({method:"isInstalled",script:he({name:e,namespace:n})}),o)}}),configurable:!0})}))}catch(e){}}})(),ve.onMessage.setListener(({method:t,args:n})=>{"load"==t?(e.pageLoaded=!0,Ce.runListeners()):"DOMContentLoaded"==t?(e.domContentLoaded=!0,Ce.runListeners()):"setForeignAttr"==t?Me[n.attr]=n.value:"port.message"==t?Re.message(n):"executeScript"==t?Ce.run(n):"cleanup"==t?ve.cleanup():r&&k("env: unkown method",t,n)}),
r&&k("Tampermonkey started"),b(e.scripts,e=>{Ce.run(e)})}},t=(self.rea,self.rea),n=self,{setTimeout:o,setInterval:r,clearTimeout:s,clearInterval:a,AbortController:i,fetch:c,XMLHttpRequest:l,webkitNotifications:d,decodeURIComponent:u,encodeURIComponent:p,Notification:m,TextDecoder:g,FileReader:f,DOMParser:_,unescape:v,escape:h,btoa:b,atob:w,alert:y,confirm:M,crypto:E,Worker:S}=(location.origin,n.forge_sha256,self),L=e=>{let t
;t=e.split(",")[0].includes("base64")?w(e.split(",")[1]):v(e.split(",")[1]);const n=e.split(",")[0].split(":")[1].split(";")[0],o=new Uint8Array(t.length);for(let e=0;e<t.length;e++)o[e]=t.charCodeAt(e);return new Blob([o],{type:n})},x=e=>new Promise(t=>{const n=new f;n.onload=e=>{var n;t((null===(n=e.target)||void 0===n?void 0:n.result)||void 0)},n.readAsDataURL(e)
}),{SHARED_OBJECT_URLS:O,SHARED_BLOBS:C,SAFARI:T}=t.FEATURES.RUNTIME,R=e=>void 0!==e.objUrl,U=e=>void 0!==e.blob,A=e=>void 0!==e.dataUri;class P{constructor(e){if(R(e))this.objUrl=e.objUrl.url,this.type=e.objUrl.type;else if(U(e))this.blob=e.blob;else{if(!A(e))throw new Error("incompatible TransferableData");this.dataUri=e.dataUri}}dispose(){this.objUrl&&URL.revokeObjectURL(this.objUrl)}async toTransferableData(){if(O){if(!this.objUrl&&(!this.blob&&this.dataUri&&(this.blob=L(this.dataUri)),
this.blob&&(this.objUrl=URL.createObjectURL(this.blob)),!this.objUrl))throw new Error("incomplete Transferable");return{objUrl:{url:this.objUrl,type:this.type}}}if(C){if(!this.blob&&(this.objUrl?this.blob=await c(this.objUrl).then(e=>e.blob()):this.dataUri&&(this.blob=L(this.dataUri)),!this.blob))throw new Error("incomplete Transferable");return{blob:this.blob}}if(T){if(!this.dataUri){let e=this.blob;if(!e&&this.objUrl&&(e=await c(this.objUrl).then(e=>e.blob())),e&&(this.dataUri=await x(e)),
!this.dataUri)throw new Error("incomplete Transferable")}return{dataUri:this.dataUri}}throw new Error("incompatible Transferable")}get tryObjectUrl(){return this.objUrl}get tryBlob(){return this.blob}get tryDataUri(){return this.dataUri}async toBlob(){if(this.blob)return this.blob;if(!this.objUrl){if(this.dataUri)return L(this.dataUri);throw new Error("incompatible Transferable")}try{return await(await c(this.objUrl)).blob()}catch(e){return}}async toDataUri(){if(this.dataUri)return this.dataUri
;{const e=await this.toBlob();if(!e)throw new Error("incompatible Transferable");return await x(e)}}static fromTransferableData(e){return e&&(U(e)||R(e)||A(e))?new P(e):void 0}}const D={addElement:["GM_addElement","GM.addElement","GM_addStyle","GM.addStyle"],cookie:["GM_cookie","GM.cookie"],readValues:["GM_listValues","GM.listValues","GM_getValue","GM.getValue","GM_addValueChangeListener","GM.addValueChangeListener","GM_removeValueChangeListener","GM.removeValueChangeListener"],
writeValues:["GM_setValue","GM.setValue","GM_deleteValue","GM.deleteValue"],download:["GM_download","GM.download"],getResource:["GM_getResourceText","GM.getResourceText","GM_getResourceURL","GM.getResourceUrl"],tabs:["GM_getTab","GM.getTab","GM_getTabs","GM.getTabs","GM_saveTab","GM.saveTab"],info:["GM_info","GM.info"],log:["GM_log","GM.log"],notification:["GM_notification","GM.notification"],openInTab:["GM_openInTab","GM.openInTab"],
menuCommand:["GM_registerMenuCommand","GM.registerMenuCommand","GM_unregisterMenuCommand","GM.unregisterMenuCommand"],setClipboard:["GM_setClipboard","GM.setClipboard"],xmlHttpRequest:["GM_xmlhttpRequest","GM.xmlHttpRequest"],"window.close":["window.close"],"window.focus":["window.focus"],"window.onurlchange":["window.onurlchange"],webRequest:["GM_webRequest","GM.webRequest"]},I=["unsafeWindow","GM_info","GM.info"],k=(Object.entries(D).reduce((e,t)=>{const[n,o]=t
;return o.forEach(t=>e[t]=[...e[t]||I,n]),e},{}),t=>{const n=t.rea;let o;const r=()=>"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,e=>{const t=16*Math.random()|0;return("x"==e?t:3&t|8).toString(16)}),s=e=>{let t;for(;t=e.shift();)t()},a=(e,t)=>{const n=document.createElementNS("http://www.w3.org/1999/xhtml",e);return"string"==typeof t?n.append(t):t&&Object.keys(t).forEach(e=>{"textContent"==e?n.textContent=t[e]:n.setAttribute(e,t[e])}),n},i=r(),c=window.self==window.top;let l=0
;const d=((e,t)=>{const o=n.FEATURES.RUNTIME.FIREFOX?e=>window.cloneInto(e,document.defaultView):e=>e,r=e=>{const t=++d;return u[d]=e,t},s=(n,r)=>{const{m:s,a,r:i,n:c}=r,l=((e,n,r)=>{let s;return r?(s=t.createEvent("MutationEvent"),s.initMutationEvent(e,!1,!1,r||null,null,null,JSON.stringify(n),s.ADDITION)):s=new window.CustomEvent(e,{detail:o(n)}),s})(n,{m:s,a,r:i},c);e.dispatchEvent.apply(e,[l])};let a,i;var c;let l;var d=1,u={};return{init:t=>{l||(l=t),c="2P_"+l,i="2C_"+l,((...t)=>{
e.addEventListener.apply(e,t)})(i,e=>{const t=(n=e).detail||JSON.parse(n.attrName);var n;if("message.response"==t.m)((e,t)=>{let n;e&&(n=u[e])&&(n(t),delete u[e])})(t.r,t.a);else if(a){const n=t.r?e=>{s(c,{m:"message.response",a:e,r:t.r})}:()=>{};a({method:t.m,args:t.a,node:e.relatedNode,sendResponse:n})}},!0)},send:(e,t,n)=>{s(c,{m:e,a:t,r:n?r(n):null})},sendToId:(e,t,n)=>{s("2P_"+e,{m:t,a:n,r:null})},onMessage:{addListener:e=>{a=e}},cleanup:()=>{((...t)=>{e.removeEventListener.apply(e,t)
})(i,a,!0)}}})(window,document),u=(()=>{const e={};let t;const n=t=>{let n=[],o=[];const r=()=>{n=null,o=null,s=null,delete e[t]};var s={postMessage:e=>{d.send("port.message",{response_id:t,value:e})},onMessage:{addListener:e=>{n.push(e)}},onDisconnect:{addListener:e=>{o.push(e)}},disconnect:()=>{d.send("port.message",{response_id:t,disconnect:!0}),r()}};return e[t]={message:e=>{n&&n.forEach(t=>{t(e)})},disconnect:e=>{o&&o.forEach(t=>{t(e)}),r()}},s};return{message:r=>{let s
;if(r.connect)t&&t(r.destination,n(r.response_id));else{if(!(s=e[r.response_id]))return void(o&&console.warn("ports: unkown id",r.response_id,r));r.disconnect?s.disconnect():s.message(r.value)}},connect:e=>{const t=r();return d.send("port.message",{response_id:t,connect:!0,destination:e}),n(t)},onConnect:{addListener:e=>{t=e}}}})(),p=(()=>{let e,t;const n=[],r=[];let a=()=>{o&&console.log("content: detected load "+i),t=!0,e=!0,c.cleanup(),s(r)};var c={init:()=>{
window.addEventListener("DOMContentLoaded",()=>{o&&console.log("content: detected DOMContentLoaded "+i),t=!0,s(n)},{capture:!1,once:!0}),window.addEventListener("load",a,!0)},registerDomListener:o=>{t||e?o():n.push(o)},registerPageListener:t=>{e?t():r.push(t)},forcedLoad:()=>{e||t||!a||(o&&console.log("content: use forced load "+i),a(!0))},seen:(()=>{const n={};return Object.defineProperties(n,{load:{get:()=>e,enumerable:!0},DOMContentLoaded:{get:()=>t,enumerable:!0}}),n})(),cleanup:()=>{
a&&(window.removeEventListener("load",a,!0),a=null)}};return c})(),m=t=>{let n=r();(r=>{const s=document.getElementsByTagName("*")[0]||document;let i=a("div");const c=i.attachShadow({mode:"closed"});c.appendChild(a("style",":host { display: none }"));const l=a("iframe",{sandbox:"allow-scripts allow-same-origin",style:"display: none",src:"javascript:void 0"});let u=()=>{if(null!==u){u=null;try{const e=l.contentDocument;if(e){const t=a("script",{textContent:r})
;e.getElementsByTagName("*")[0].appendChild(t)}}catch(e){}(r=>{const s="("+e.backup+')(window, document,"'+n+'",'+o+","+e.args.join(",")+");\n",i=a("script",{textContent:s});r.appendChild(i),p.init(),d.sendToId(n,"commid",{id:t})})(i),l.remove(),i.remove()}};l.addEventListener("load",u,{once:!0,capture:!0}),c.appendChild(l),s.appendChild(i),u&&u()})("("+((e,t)=>{window.parent[e]=t(window)}).toString()+')("'+n+'", '+e.args[0]+")")},g=()=>{d.send("cleanup")},f=(()=>{const e={setInterval:e=>{let t
;e.onMessage.addListener(n=>{"setInterval"==n.method&&(t=window.setInterval(e.postMessage,n.t))}),e.onDisconnect.addListener(()=>{t&&window.clearInterval(t),t=null})},registerMenuCommand:e=>{const t=n.extension.connect("registerMenuCommand");t.onMessage.addListener(n=>{if(null!==t){const{method:t,event:o}=n;e.postMessage({method:t,event:o})}}),t.onDisconnect.addListener(()=>{e.disconnect()}),e.onMessage.addListener(e=>{if("register"!==e.method)return
;const{name:n,uuid:o,accessKey:r}=e,s=[i,n,o].join("#");t.postMessage({method:"registerMenuCommand",name:n,uuid:o,menuId:s,accessKey:r})}),e.onDisconnect.addListener(()=>{t.disconnect()})},openInTab:e=>{const t=n.extension.connect("openInTab");t.onMessage.addListener(t=>{e.postMessage(t)}),t.onDisconnect.addListener(()=>{e.disconnect()}),e.onMessage.addListener(e=>{if("openTab"==e.method){let n=e.url,o=e.options;"boolean"!=typeof o&&void 0!==o||(o={loadInBackground:o})
;const r=void 0===o.active?void 0!==o.loadInBackground&&!o.loadInBackground:o.active,s=void 0===o.insert||o.insert;n&&0===n.search(/^\/\//)&&(n=location.protocol+n),t.postMessage({method:"openInTab",details:{url:n,options:{active:!!r,insert:!!s,incognito:!!o.incognito,setParent:!o.incognito&&!!o.setParent}},uuid:e.uuid})}else void 0!==e.name?t.postMessage({name:e.name,uuid:e.uuid}):e.focus?t.postMessage({focus:!0,uuid:e.uuid}):e.close&&t.postMessage({close:!0,uuid:e.uuid})}),
e.onDisconnect.addListener(()=>{t.disconnect()})},download:e=>{const t=n.extension.connect("download");t.onMessage.addListener(t=>{e.postMessage(t)}),t.onDisconnect.addListener(()=>{e.disconnect()}),e.onMessage.addListener(e=>{if(e.cancel)t.postMessage({cancel:!0,id:i,uuid:e.uuid});else{const n=e.details;let o=n.url;delete n.url,o&&"/"===o[0]&&(o=location.origin+o),t.postMessage({method:"download",details:{from:{url:o},...n},id:i,uuid:e.uuid})}}),e.onDisconnect.addListener(()=>{t.disconnect()})
},webRequest:e=>{const t=n.extension.connect("webRequest");t.onMessage.addListener(t=>{e.postMessage(t)}),t.onDisconnect.addListener(()=>{e.disconnect()}),e.onMessage.addListener(e=>{t.postMessage({method:"webRequest",rules:e.rules,uuid:e.uuid})}),e.onDisconnect.addListener(()=>{t.disconnect()})},xhr:e=>{let t,o;const r=[],s=async e=>{if(e&&r.push(e),o)await o,s();else{const e=r.shift();e&&e()}},a=n.extension.connect("xhr");a.onMessage.addListener(t=>{s(()=>{const{onpartial:n,data:r}=t
;if(n&&r&&r.tfd){const n=P.fromTransferableData(r.tfd);return delete r.tfd,void(o=new Promise(s=>{let a;n.toBlob().then(e=>(a=e.type,e.arrayBuffer?e.arrayBuffer():new Response(e).arrayBuffer())).then(i=>{r.nada={buffer:i,type:a},e.postMessage(t),o=null,s(),n.dispose()}).catch(e=>console.warn(e))}))}e.postMessage(t)})}),a.onDisconnect.addListener(()=>{s(async()=>{e.disconnect()})}),e.onMessage.addListener(e=>{t=t||e.details,a.postMessage(e)}),e.onDisconnect.addListener(()=>{a.disconnect()})},
onurlchange:e=>{const t=n.extension.connect("onurlchange");let o=()=>{e.postMessage({url:document.location.href})};const r=()=>{o&&(window.removeEventListener("hashchange",o),o=null)};window.addEventListener("hashchange",o),t.onMessage.addListener(t=>{e.postMessage(t)}),t.onDisconnect.addListener(()=>{e.disconnect(),r()}),e.onMessage.addListener(e=>{t.postMessage(e)}),e.onDisconnect.addListener(()=>{t.disconnect(),r()})},values:e=>{const t=n.extension.connect("values")
;t.onMessage.addListener(t=>{e.postMessage(t)}),t.onDisconnect.addListener(()=>{e.disconnect()}),e.onMessage.addListener(e=>{t.postMessage(e)}),e.onDisconnect.addListener(()=>{t.disconnect()})}},t={setTimeout:({args:e,cb:t})=>{window.setTimeout(t,e.t)},setClipboard:({args:e,cb:t})=>{const o=e.content,r=e.info,s=typeof r;let a,i;"object"===s?(r.type&&(a=r.type),r.mimetype&&(i=r.mimetype)):"string"===s&&(a=r);const c=i||("html"==a?"text/html":"text/plain")
;n.FEATURES.RUNTIME.CLIPBOARD_API?n.extension.sendMessage({method:"clipboard",mimetype:c,content:o},()=>t()):(document.addEventListener("copy",e=>{e.stopImmediatePropagation(),e.preventDefault(),e.clipboardData.setData(c,o)},{capture:!0,once:!0}),document.execCommand("copy"),t())},notification:({args:e,cb:t})=>{e.method="notification",n.extension.sendMessage(e,t)},syntaxCheck:({args:e,cb:t})=>{e.method="syntaxCheck",n.extension.sendMessage(e,t)},closeTab:({args:{uuid:e},cb:t})=>{
n.extension.sendMessage({method:"closeTab",uuid:e,id:i},e=>{e.error&&console.warn(e.error),t()})},focusTab:({args:{uuid:e},cb:t})=>{n.extension.sendMessage({method:"focusTab",uuid:e,id:i},e=>{e.error&&console.warn(e.error),t()})},addElement:async({args:e,node:t,cb:n})=>{try{const o=a(e.tag,{...e.properties||{},...e.id?{id:e.id}:{}});let r;t?r=t:(r=document.head||document.body||document.documentElement,r||(r=await new Promise(e=>p.registerDomListener(()=>e(document.head||document.body))))),
r.appendChild(o),n()}catch(e){console.warn("content: error adding script",e)}},tabs:({args:e,cb:t})=>{e.method="tabs",n.extension.sendMessage(e,e=>{t(e.data)})},cookie:({args:e,cb:t})=>{e.method="cookie",n.extension.sendMessage(e,e=>{t(e.data)})}};return{init:()=>{},processMessage:({method:e,args:n,node:o,sendResponse:r})=>{let s;if(s=t[e])return s({args:n,node:o,cb:r});r()},processConnect:(t,n)=>{let o;if(o=e[t])return o(n)}}})()
;(n.FEATURES.RUNTIME.FIREFOX?new Promise(e=>p.registerDomListener(()=>e(document.body))):Promise.resolve(document)).then(e=>{e.addEventListener("mouseenter",()=>{n.extension.sendMessage({method:"contextmenu",url:window.location.href,id:i})},!1)}),n.extension.onMessage.addListener((e,t,n)=>{
if(e.id&&e.id!=i)console.warn("content: Not for me! "+i.substr(0,10)+"!="+e.id);else if("executeScript"==e.method)e.url&&0!==window.location.href.indexOf(e.url)?o&&console.log("exec: URL doesn't match",window.location,e):void 0!==e.topframe&&e.topframe!=c?o&&console.log("exec: topframe doesn't match",window.self,e):d.send("executeScript",e),n({});else if("onLoad"==e.method)document.readyState&&"complete"!==document.readyState||p.forcedLoad(),
n({});else if(c)if("loadUrl"==e.method)window.location=e.url,n({});else if("reload"==e.method)window.location.reload(),n({});else{if("confirm"==e.method)return window.setTimeout(()=>{const t=window.confirm(e.msg);n({confirm:t})},100),!0;if("showMsg"==e.method)return window.setTimeout(()=>{window.setTimeout(()=>{window.alert(e.msg)},1),n({})},100),!0;"setForeignAttr"==e.method?(d.send(e.method,e),n({})):window.console.log("content: unknown method "+e.method)}}),u.onConnect.addListener((e,t)=>{
f.processConnect(e,t)}),d.onMessage.addListener(e=>{const{method:t,args:o,sendResponse:r}=e;if("document.write"==t){const e=document.documentElement;Promise.resolve().then(()=>{e!==document.documentElement&&d.init()})}else"port.message"==t?u.message(o):"csp"==t?n.page.eval(o.src):"external.message"==t?n.extension.sendMessage({method:"externalMessage",request:o},e=>{r(e)}):f.processMessage(e)});let _=!1;const v=(e,t,r)=>{let s=1;const a=()=>{o&&console.debug('content: send "prepare" message'),
n.extension.sendMessage({method:"prepare",id:i,topframe:c,url:window.location.href},n=>{if(!_){if(!n)return o&&console.debug("content: _early_ execution, connection to bg failed -> retry!"),window.setTimeout(a,s),void(s*=2);_=!0,n.contexters||n.scripts&&n.scripts.length||n.external_connect?(r&&r(),t(n)):(g(),e())}})};n.content.onReady(a)
},h=location.pathname+location.search,b="TM_"+n.runtime.short_id+window.btoa(h.length+h).substr(0,255).replace(/[#=\/]/g,"_"),w=document.contentType&&"text/html"!=document.contentType;var y,M,E;y=(e,r)=>{let s;o&&console.log("content: Started ("+i+", "+window.location.origin+window.location.pathname+")",t.tm_info),n.FEATURES.RUNTIME.FAST_EXEC_SUPPORT&&(s=(()=>{let e,t,o,r;try{r=document.cookie.split(";")}catch(e){return}for(e=0;e<r.length;e++)if(t=r[e].substr(0,r[e].indexOf("=")),
o=r[e].substr(r[e].indexOf("=")+1),t=t.replace(/^\s+|\s+$/g,""),0===t.indexOf(b)){document.cookie=t+"=; expires=Thu, 01 Jan 1970 00:00:01 GMT;";const e=window.decodeURIComponent(o);if(0!==e.indexOf("blob:"))continue;let r;try{if(0!==(new URL(e).origin+"/").indexOf(n.extension.getURL("/")))continue;if(r=new XMLHttpRequest,r.open("GET",e,!1),r.send(null),200===r.status||0===r.status)return JSON.parse(r.responseText)}catch(e){console.warn("content: unable to decode "+(r&&r.responseText||"unknown"))
}}})())||(s=t.tm_info)?(delete t.tm_info,s.contexters||s.scripts&&s.scripts.length||s.external_connect?(m(i),d.init(i),r(s,"sync")):e(),n.FEATURES.RUNTIME.FAST_EXEC_SUPPORT&&n.extension.sendMessage({method:"prepare",url:window.location.href,cleanup:!0},()=>{})):w?v(e,r,()=>{m(i),d.init(i)}):(m(i),d.init(i),v(e,r))},M=()=>{o&&console.log("content: disable event processing for "+i),p.cleanup(),g(),d.cleanup()},E=(t,r)=>{l=t.logLevel,o|=l>=60,p.registerDomListener(()=>{d.send("DOMContentLoaded")}),
p.registerPageListener(()=>{d.send("load")}),o&&console.log("content: "+(r||"normal")+" start event processing for "+i+" ("+t.scripts.length+" to run)"),f.init(t.scripts),(t=>{const r={short_id:n.runtime.short_id};["inIncognitoContext","isFirstPartyIsolation","downloadMode","enforce_strict_mode","top_level_await","measure_scripts","version","external_connect"].forEach(e=>{r[e]=t[e]}),r.sandbox_allow_getters=!0,r.detect_constructors_by_keys=n.FEATURES.RUNTIME.DETECT_CONSTRUCTORS_BY_KEYS,
r.blob_download_supported=!n.FEATURES.RUNTIME.FIREFOX,o&&(p.seen.load?console.log("content: Start ENV with page loaded "+i):p.seen.DOMContentLoaded?console.log("content: Start ENV with DOMContentLoaded "+i):console.log("content: Start ENV normally "+i));const s=e.next(i,JSON.stringify(t.scripts),JSON.stringify(r),JSON.stringify({}),JSON.stringify(D),l,void 0,void 0,void 0,void 0,o,p.seen.load,p.seen.DOMContentLoaded,e.environment),a="__c__"+(19831206*Math.random()+1);d.send("next",{id:a})
;const c='window["'+a+'"] = function(){'+s+"};";n.page.eval(c)})(t),c||window.addEventListener("unload",()=>{n.extension.sendMessage({method:"unLoad",id:i,topframe:!1,url:window.location.href},()=>{}),p.cleanup(),g(),d.cleanup()},!0)},w?window.setTimeout(()=>{y(M,E)},1):y(M,E)});(async e=>{if(!{"http:":!0,"https:":!0,"file:":!0}[e.location.protocol])return;const t=e.rea;void 0===t.globals._content&&(t.globals._content=!0,k(window))})(window)})();